name: Docker build and push

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag qwerty467/roommate-front:${{ github.run_number }}

    - name: Push Docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: qwerty467/roommate-front
        tags: roommate-front:${{ github.run_number }}
        registry: docker.io
        dockerfile: Dockerfile
        buildArgs: EMAIL,PASSWORD
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


          # - envsubst < kubedeploy.yaml | kubectl apply -f -
